version: "3.9"

services:
  account_service:
    build:
      context: ./account_service
    container_name: account_service
    ports:
      - "8001:8001"

  gateway_service:
    build:
      context: ./gateway_service
    container_name: gateway_service
    ports:
      - "8000:8000"
    depends_on:
      - account_service